"""add_payment_fields

Revision ID: 1922f88b5aec
Revises: 77a9bca33360
Create Date: 2025-10-03 01:03:50.818649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1922f88b5aec'
down_revision = '77a9bca33360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_key_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_key_secret', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('organizer_account_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('payment_enabled')
        batch_op.drop_column('organizer_account_id')
        batch_op.drop_column('razorpay_key_secret')
        batch_op.drop_column('razorpay_key_id')

    # ### end Alembic commands ###
