"""Add new fields to Event model

Revision ID: 77a9bca33360
Revises: 
Create Date: 2025-09-05 15:11:46.213368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a9bca33360'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('timing', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('event_list', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('event_type')
        batch_op.drop_column('contact')
        batch_op.drop_column('event_list')
        batch_op.drop_column('registration_type')
        batch_op.drop_column('timing')
        batch_op.drop_column('department')
        batch_op.drop_column('club_name')

    # ### end Alembic commands ###
